In [3]:
import pandas as pd
import numpy as np

In [4]:
## PREPROCESS THE DATA
UsdJpyH1_pd = pd.read_csv('2018-08-17-UsdChfH1_raw.csv')
UsdJpyH1_pd

## Rename Columns to: Time, Open, High, Low, Close, Volume
UsdJpyH1_pd.columns = ['Date', 'Time', 'Open','High','Low','Close', 'Volume']
UsdJpyH1_zero = UsdJpyH1_pd

## Set Index to Date for Accuracy
UsdJpyH1_date = UsdJpyH1_zero.set_index('Date')

In [5]:
# Creating the "TIME" table

T00UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '00:00')]
T01UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '01:00')]
T02UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '02:00')]
T03UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '03:00')]
T04UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '04:00')]
T05UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '05:00')]
T06UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '06:00')]
T07UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '07:00')]
T08UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '08:00')]
T09UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '09:00')]
T10UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '10:00')]
T11UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '11:00')]
T12UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '12:00')]
T13UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '13:00')]
T14UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '14:00')]
T15UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '15:00')]
T16UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '16:00')]
T17UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '17:00')]
T18UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '18:00')]
T19UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '19:00')]
T20UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '20:00')]
T21UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '21:00')]
T22UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '22:00')]
T23UsdJpy_date = UsdJpyH1_date [(UsdJpyH1_date ['Time'] == '23:00')]

In [6]:
# Reshaping table to horizontal, with date as index

T00UsdJpy_date.columns = ['T00', 'O00','H00','L00','C00','Vol']
T01UsdJpy_date.columns = ['T01', 'O01','H01','L01','C01','Vol']
T02UsdJpy_date.columns = ['T02', 'O02','H02','L02','C02','Vol']
T03UsdJpy_date.columns = ['T03', 'O03','H03','L03','C03','Vol']
T04UsdJpy_date.columns = ['T04', 'O04','H04','L04','C04','Vol']
T05UsdJpy_date.columns = ['T05', 'O05','H05','L05','C05','Vol']
T06UsdJpy_date.columns = ['T06', 'O06','H06','L06','C06','Vol']
T07UsdJpy_date.columns = ['T07', 'O07','H07','L07','C07','Vol']
T08UsdJpy_date.columns = ['T08', 'O08','H08','L08','C08','Vol']
T09UsdJpy_date.columns = ['T09', 'O09','H09','L09','C09','Vol']
T10UsdJpy_date.columns = ['T10', 'O10','H10','L10','C10','Vol']
T11UsdJpy_date.columns = ['T11', 'O11','H11','L11','C11','Vol']
T12UsdJpy_date.columns = ['T12', 'O12','H12','L12','C12','Vol']
T13UsdJpy_date.columns = ['T13', 'O13','H13','L13','C13','Vol']
T14UsdJpy_date.columns = ['T14', 'O14','H14','L14','C14','Vol']
T15UsdJpy_date.columns = ['T15', 'O15','H15','L15','C15','Vol']
T16UsdJpy_date.columns = ['T16', 'O16','H16','L16','C16','Vol']
T17UsdJpy_date.columns = ['T17', 'O17','H17','L17','C17','Vol']
T18UsdJpy_date.columns = ['T18', 'O18','H18','L18','C18','Vol']
T19UsdJpy_date.columns = ['T19', 'O19','H19','L19','C19','Vol']
T20UsdJpy_date.columns = ['T20', 'O20','H20','L20','C20','Vol']
T21UsdJpy_date.columns = ['T21', 'O21','H21','L21','C21','Vol']
T22UsdJpy_date.columns = ['T22', 'O22','H22','L22','C22','Vol']
T23UsdJpy_date.columns = ['T23', 'O23','H23','L23','C23','Vol']

Table_Horizontal_date = pd.concat([T00UsdJpy_date, T01UsdJpy_date, T02UsdJpy_date, T03UsdJpy_date, T04UsdJpy_date, T05UsdJpy_date, T06UsdJpy_date, T07UsdJpy_date, T08UsdJpy_date, T09UsdJpy_date, T10UsdJpy_date, T11UsdJpy_date, T12UsdJpy_date, T13UsdJpy_date, T14UsdJpy_date, T15UsdJpy_date, T16UsdJpy_date, T17UsdJpy_date, T18UsdJpy_date, T19UsdJpy_date, T20UsdJpy_date, T21UsdJpy_date, T22UsdJpy_date, T23UsdJpy_date], axis=1)
Table_Horizontal_date

/home/me/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:28: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,T00,O00,H00,L00,C00,Vol,T01,O01,H01,L01,...,H22,L22,C22,Vol,T23,O23,H23,L23,C23,Vol
2015.01.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.01502,1.01341,1.01484,4761.0,23:00,1.01485,1.01485,1.01415,1.01432,2479.0
2015.01.08,00:00,1.01432,1.01482,1.01415,1.01478,1375.0,01:00,1.01478,1.01500,1.01451,...,1.01928,1.01855,1.01882,2622.0,23:00,1.01882,1.01882,1.01808,1.01835,2368.0
2015.01.09,00:00,1.01833,1.01893,1.01817,1.01867,1454.0,01:00,1.01867,1.01898,1.01831,...,1.01478,1.01397,1.01406,3434.0,23:00,1.01407,1.01500,1.01383,1.01414,1688.0
2015.01.12,00:00,1.01398,1.01399,1.01178,1.01194,1420.0,01:00,1.01195,1.01291,1.01180,...,1.01488,1.01426,1.01452,2436.0,23:00,1.01453,1.01495,1.01451,1.01481,1355.0
2015.01.13,00:00,1.01490,1.01528,1.01466,1.01525,1036.0,01:00,1.01527,1.01542,1.01496,...,1.02129,1.01995,1.02020,5084.0,23:00,1.02021,1.02026,1.01963,1.02004,1781.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018.08.13,00:00,0.99316,0.99462,0.99244,0.99278,579.0,01:00,0.99302,0.99444,0.99302,...,0.99413,0.99323,0.99323,1741.0,23:00,0.99323,0.99339,0.99292,0.99298,1055.0
2018.08.14,00:00,0.99330,0.99340,0.99162,0.99283,1440.0,01:00,0.99285,0.99339,0.99283,...,0.99455,0.99395,0.99411,1295.0,23:00,0.99411,0.99446,0.99410,0.99412,854.0
2018.08.15,00:00,0.99407,0.99415,0.99271,0.99376,733.0,01:00,0.99375,0.99419,0.99375,...,0.99339,0.99258,0.99337,2586.0,23:00,0.99337,0.99367,0.99301,0.99361,1127.0
2018.08.16,00:00,0.99341,0.99386,0.99301,0.99349,1984.0,01:00,0.99345,0.99379,0.99335,...,0.99713,0.99641,0.99656,1859.0,23:00,0.99655,0.99690,0.99633,0.99689,778.0
2018.08.17,00:00,0.99667,0.99699,0.99635,0.99681,1798.0,01:00,0.99681,0.99717,0.99678,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# PREMONITION by ANALYTICS
# Create table for entry direction decisions
# Price change from Open 09 to Close 11

EntryDirection = Table_Horizontal_date['C11'] - Table_Horizontal_date['O09']
EntryDirection = pd.DataFrame (EntryDirection, columns = ['CALC'])
EntryDirection['POS'] = 'Default'
EntryDirection['POS'][EntryDirection['CALC'] > 0] = 'Long'
EntryDirection['POS'][EntryDirection['CALC'] < 0] = 'Short'

EntryDirection_date = EntryDirection

/home/me/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/me/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [8]:
# Calculate HIghs and Lows for 12:00 to 18:00

High_12TO18 = Table_Horizontal_date [['H12','H13','H14', 'H15', 'H16', 'H17', 'H18']]
High_12TO18['H1218'] = High_12TO18.max(axis=1)

Low_12TO18 = Table_Horizontal_date [['L12','L13','L14', 'L15', 'L16', 'L17', 'L18']]
Low_12TO18['L1218'] = Low_12TO18.min(axis=1)

/home/me/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/home/me/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [9]:
# Create table for Closing 03:00
UsdJpyC11 = T11UsdJpy_date[['C11']]
UsdJpyO09 = T09UsdJpy_date[['O09']]

In [10]:
# Concatenate the tables
Table_HighLowClosePosition = pd.concat([UsdJpyO09, High_12TO18, Low_12TO18, UsdJpyC11, EntryDirection_date], axis=1)
Table_HighLowClosePosition
# Cleanup
# Table_HighLowClosePosition = Table_HighLowClosePosition[['H0410', 'L0410','C03', 'POS']]
# Table_HighLowClosePosition

/home/me/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,O09,H12,H13,H14,H15,H16,H17,H18,H1218,L12,L13,L14,L15,L16,L17,L18,L1218,C11,CALC,POS
2015.01.07,1.01202,1.01411,1.01609,1.01599,1.01613,1.01699,1.01754,1.01755,1.01755,1.01121,1.01300,1.01389,1.01457,1.01506,1.01505,1.01543,1.01121,1.01311,0.00109,Long
2015.01.08,1.01608,1.02092,1.02096,1.02166,1.02106,1.01947,1.02006,1.01871,1.02166,1.01890,1.01991,1.01952,1.01869,1.01781,1.01785,1.01661,1.01661,1.01926,0.00318,Long
2015.01.09,1.01849,1.01723,1.01701,1.01693,1.02093,1.02003,1.01915,1.01575,1.02093,1.01608,1.01602,1.01615,1.01498,1.01800,1.01439,1.01379,1.01379,1.01639,-0.00210,Short
2015.01.12,1.01292,1.01834,1.01871,1.01894,1.01862,1.01683,1.01629,1.01692,1.01894,1.01640,1.01700,1.01735,1.01549,1.01383,1.01399,1.01497,1.01383,1.01659,0.00367,Long
2015.01.13,1.01522,1.01862,1.01888,1.01981,1.02059,1.02146,1.02175,1.02015,1.02175,1.01678,1.01684,1.01781,1.01825,1.01949,1.01809,1.01773,1.01678,1.01700,0.00178,Long
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018.08.13,0.99324,0.99524,0.99489,0.99490,0.99496,0.99462,0.99431,0.99392,0.99524,0.99457,0.99420,0.99397,0.99389,0.99320,0.99329,0.99308,0.99308,0.99477,0.00153,Long
2018.08.14,0.99403,0.99333,0.99164,0.99097,0.99174,0.99161,0.99339,0.99353,0.99353,0.99119,0.99021,0.99033,0.99008,0.99081,0.99014,0.99230,0.99008,0.99315,-0.00088,Short
2018.08.15,0.99630,0.99796,0.99824,0.99788,0.99747,0.99764,0.99659,0.99498,0.99824,0.99705,0.99751,0.99700,0.99639,0.99636,0.99398,0.99358,0.99358,0.99718,0.00088,Long
2018.08.16,0.99203,0.99374,0.99414,0.99416,0.99403,0.99439,0.99509,0.99623,0.99623,0.99263,0.99311,0.99328,0.99245,0.99270,0.99295,0.99437,0.99245,0.99311,0.00108,Long
2018.08.17,0.99697,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Default

In [11]:
# Calculate Success Rate

LongPosition = Table_HighLowClosePosition ['H1218'] - Table_HighLowClosePosition ['C11']
LongPosition = pd.DataFrame (LongPosition, columns = ['PIP LONG'])

ShortPosition = Table_HighLowClosePosition ['C11'] - Table_HighLowClosePosition ['L1218']
ShortPosition = pd.DataFrame (ShortPosition, columns = ['PIP SHORT'])

In [12]:
Table_HighLowClosePosition = pd.concat([Table_HighLowClosePosition, LongPosition, ShortPosition], axis=1)
Table_HighLowClosePosition

,O09,H12,H13,H14,H15,H16,H17,H18,H1218,L12,...,L15,L16,L17,L18,L1218,C11,CALC,POS,PIP LONG,PIP SHORT
2015.01.07,1.01202,1.01411,1.01609,1.01599,1.01613,1.01699,1.01754,1.01755,1.01755,1.01121,...,1.01457,1.01506,1.01505,1.01543,1.01121,1.01311,0.00109,Long,0.00444,0.00190
2015.01.08,1.01608,1.02092,1.02096,1.02166,1.02106,1.01947,1.02006,1.01871,1.02166,1.01890,...,1.01869,1.01781,1.01785,1.01661,1.01661,1.01926,0.00318,Long,0.00240,0.00265
2015.01.09,1.01849,1.01723,1.01701,1.01693,1.02093,1.02003,1.01915,1.01575,1.02093,1.01608,...,1.01498,1.01800,1.01439,1.01379,1.01379,1.01639,-0.00210,Short,0.00454,0.00260
2015.01.12,1.01292,1.01834,1.01871,1.01894,1.01862,1.01683,1.01629,1.01692,1.01894,1.01640,...,1.01549,1.01383,1.01399,1.01497,1.01383,1.01659,0.00367,Long,0.00235,0.00276
2015.01.13,1.01522,1.01862,1.01888,1.01981,1.02059,1.02146,1.02175,1.02015,1.02175,1.01678,...,1.01825,1.01949,1.01809,1.01773,1.01678,1.01700,0.00178,Long,0.00475,0.00022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018.08.13,0.99324,0.99524,0.99489,0.99490,0.99496,0.99462,0.99431,0.99392,0.99524,0.99457,...,0.99389,0.99320,0.99329,0.99308,0.99308,0.99477,0.00153,Long,0.00047,0.00169
2018.08.14,0.99403,0.99333,0.99164,0.99097,0.99174,0.99161,0.99339,0.99353,0.99353,0.99119,...,0.99008,0.99081,0.99014,0.99230,0.99008,0.99315,-0.00088,Short,0.00038,0.00307
2018.08.15,0.99630,0.99796,0.99824,0.99788,0.99747,0.99764,0.99659,0.99498,0.99824,0.99705,...,0.99639,0.99636,0.99398,0.99358,0.99358,0.99718,0.00088,Long,0.00106,0.00360
2018.08.16,0.99203,0.99374,0.99414,0.99416,0.99403,0.99439,0.99509,0.99623,0.99623,0.99263,...,0.99245,0.99270,0.99295,0.99437,0.99245,0.99311,0.00108,Long,0.00312,0.00066
2018.08.17,0.99697,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Default,NaN,NaN

In [13]:
# Capture all Long and Short Positions

SummaryLongPosition = Table_HighLowClosePosition[(Table_HighLowClosePosition['POS'] == 'Long')]
SummaryShortPosition = Table_HighLowClosePosition[(Table_HighLowClosePosition['POS'] == 'Short')]

In [14]:
# For long position result
LongPosSubResult = np.where (SummaryLongPosition ['PIP LONG'] > 0.0008, 'Success', 'Fail')
LongPosSubResult = pd.DataFrame (LongPosSubResult, columns = ['LONG RESULT'])
LongPosSubResult

# Isolate BuyPosSubResult_pd
LongPosSubResult_x = LongPosSubResult

# Convert To Numpy 
LongPosSubResult_np = LongPosSubResult_x.values

# Count Contents
countTotalResultForLong = len(LongPosSubResult_np)
countSuccessResultLong = (LongPosSubResult_np == 'Success').sum() 

WinRateForLongPos = countSuccessResultLong / countTotalResultForLong
WinRateForLongPos

0.8311965811965812

In [15]:
ShortPosSubResult = np.where (SummaryShortPosition ['PIP SHORT'] > 0.0008, 'Success', 'Fail')
ShortPosSubResult = pd.DataFrame (ShortPosSubResult, columns = ['SHORT RESULT'])
ShortPosSubResult  

# Isolate SellPosSubResult_pd
ShortPosSubResult_x = ShortPosSubResult

# Convert To Numpy
ShortPosSubResult_np = ShortPosSubResult_x.values

# Count Contents
countTotalResultForShort = len(ShortPosSubResult_np)
countSuccessResultShort = (ShortPosSubResult_np == 'Success').sum() 

WinRateForShortPos = countSuccessResultShort / countTotalResultForShort
WinRateForShortPos

0.7858672376873662